### PR TITLE
RFC: Rebase?

### PR DESCRIPTION
**Pull request by michalt**
Hi, I'm trying to understand what changes you've done and what is the status. And not being able to compare with HEAD is a bit of a pain. Merging is not trivial either, since there are a bunch of merge conflicts, so I've tried to rebase all your commits on top of current HEAD (slightly easier to deal with conflicts, since there are fewer things changing at a time). Also, I'd be inclined to squash most of it, but leaving it as is for now. 

Anyway, I'm not sure this is actually useful for you (feel free to close this if it's not!), but I'm uploading it just in case.

Btw. how are things going with the LLVM part? Are you aiming for LLVM 7?

### CODE REVIEW

**Comment by michalt** [comment]
(btw. if this is useful, I'd probably just manually do a `git reset`)

**Comment by kavon** [comment]
I'm also not sure if rebase vs merge is useful, since I need to fix the conflicts anyways. I do intend to start working on this again very soon*, and the first thing I plan to do is catch up with GHC master and fix the remaining FFI issues on the GHC side.

In terms of the LLVM side, I will mostly be reworking the implementation to make the patch clean and robust.

(*) I've been consumed by a rather important and difficult debug for a different project for the past two weeks 😒

**Comment by kavon** [comment]
I also looked into how painful a rebase would be and decided I'll stick with merging.

I've caught up to a newer version of `master` if you want to take a look at things, here's the commit: 4a6eb165ba46f3447d44f1550c9e5e2e2d4bc421

Now that I have found some time, I'm currently working on getting more of the test suite to pass.

**Comment by michalt** [comment]
Sure, sounds good! Lets close this then. :)
(though the linked merge commit doesn't make it easy to understand the changes: `Showing 1,144 changed files with 35,869 additions and 12,791 deletions.` ;)
Have you considered uploading this to Phab? (and marking it as WIP)

**Comment by kavon** [comment]
> Have you considered uploading this to Phab? (and marking it as WIP)

That's a good idea. I'm not sure if I should do it now or once the GHC side of things are more stable (I'm thinking mostly of #6 which will need some larger changes).

> though the linked merge commit doesn't make it easy to understand the changes

Right now I'm using  `git diff d9d463289fe20316cff12a8f0dbf414db678fa72 HEAD` to inspect the changes I've made against the master branch. That commit hash is mentioned in the merge commit here 4a6eb165ba46f3447d44f1550c9e5e2e2d4bc421 . That's how I keep merge commits manageable :)

**Pull request closed without merging**
